/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProgramasRouteImport } from './routes/programas'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as GatilhoRouteImport } from './routes/gatilho'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ComprovarRouteImport } from './routes/comprovar'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as BackofficeRouteImport } from './routes/backoffice'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtecaoIndexRouteImport } from './routes/protecao.index'
import { Route as LavouraIndexRouteImport } from './routes/lavoura.index'
import { Route as ProtecaoConfirmadoRouteImport } from './routes/protecao.confirmado'
import { Route as LavouraAcaoRouteImport } from './routes/lavoura.acao'

const ProgramasRoute = ProgramasRouteImport.update({
  id: '/programas',
  path: '/programas',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const GatilhoRoute = GatilhoRouteImport.update({
  id: '/gatilho',
  path: '/gatilho',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprovarRoute = ComprovarRouteImport.update({
  id: '/comprovar',
  path: '/comprovar',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const BackofficeRoute = BackofficeRouteImport.update({
  id: '/backoffice',
  path: '/backoffice',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtecaoIndexRoute = ProtecaoIndexRouteImport.update({
  id: '/protecao/',
  path: '/protecao/',
  getParentRoute: () => rootRouteImport,
} as any)
const LavouraIndexRoute = LavouraIndexRouteImport.update({
  id: '/lavoura/',
  path: '/lavoura/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtecaoConfirmadoRoute = ProtecaoConfirmadoRouteImport.update({
  id: '/protecao/confirmado',
  path: '/protecao/confirmado',
  getParentRoute: () => rootRouteImport,
} as any)
const LavouraAcaoRoute = LavouraAcaoRouteImport.update({
  id: '/lavoura/acao',
  path: '/lavoura/acao',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backoffice': typeof BackofficeRoute
  '/cadastro': typeof CadastroRoute
  '/comprovar': typeof ComprovarRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/gatilho': typeof GatilhoRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRoute
  '/programas': typeof ProgramasRoute
  '/lavoura/acao': typeof LavouraAcaoRoute
  '/protecao/confirmado': typeof ProtecaoConfirmadoRoute
  '/lavoura/': typeof LavouraIndexRoute
  '/protecao/': typeof ProtecaoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/backoffice': typeof BackofficeRoute
  '/cadastro': typeof CadastroRoute
  '/comprovar': typeof ComprovarRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/gatilho': typeof GatilhoRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRoute
  '/programas': typeof ProgramasRoute
  '/lavoura/acao': typeof LavouraAcaoRoute
  '/protecao/confirmado': typeof ProtecaoConfirmadoRoute
  '/lavoura': typeof LavouraIndexRoute
  '/protecao': typeof ProtecaoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backoffice': typeof BackofficeRoute
  '/cadastro': typeof CadastroRoute
  '/comprovar': typeof ComprovarRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/gatilho': typeof GatilhoRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRoute
  '/programas': typeof ProgramasRoute
  '/lavoura/acao': typeof LavouraAcaoRoute
  '/protecao/confirmado': typeof ProtecaoConfirmadoRoute
  '/lavoura/': typeof LavouraIndexRoute
  '/protecao/': typeof ProtecaoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/backoffice'
    | '/cadastro'
    | '/comprovar'
    | '/configuracoes'
    | '/gatilho'
    | '/onboarding'
    | '/perfil'
    | '/programas'
    | '/lavoura/acao'
    | '/protecao/confirmado'
    | '/lavoura/'
    | '/protecao/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/backoffice'
    | '/cadastro'
    | '/comprovar'
    | '/configuracoes'
    | '/gatilho'
    | '/onboarding'
    | '/perfil'
    | '/programas'
    | '/lavoura/acao'
    | '/protecao/confirmado'
    | '/lavoura'
    | '/protecao'
  id:
    | '__root__'
    | '/'
    | '/backoffice'
    | '/cadastro'
    | '/comprovar'
    | '/configuracoes'
    | '/gatilho'
    | '/onboarding'
    | '/perfil'
    | '/programas'
    | '/lavoura/acao'
    | '/protecao/confirmado'
    | '/lavoura/'
    | '/protecao/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BackofficeRoute: typeof BackofficeRoute
  CadastroRoute: typeof CadastroRoute
  ComprovarRoute: typeof ComprovarRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  GatilhoRoute: typeof GatilhoRoute
  OnboardingRoute: typeof OnboardingRoute
  PerfilRoute: typeof PerfilRoute
  ProgramasRoute: typeof ProgramasRoute
  LavouraAcaoRoute: typeof LavouraAcaoRoute
  ProtecaoConfirmadoRoute: typeof ProtecaoConfirmadoRoute
  LavouraIndexRoute: typeof LavouraIndexRoute
  ProtecaoIndexRoute: typeof ProtecaoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/programas': {
      id: '/programas'
      path: '/programas'
      fullPath: '/programas'
      preLoaderRoute: typeof ProgramasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gatilho': {
      id: '/gatilho'
      path: '/gatilho'
      fullPath: '/gatilho'
      preLoaderRoute: typeof GatilhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comprovar': {
      id: '/comprovar'
      path: '/comprovar'
      fullPath: '/comprovar'
      preLoaderRoute: typeof ComprovarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backoffice': {
      id: '/backoffice'
      path: '/backoffice'
      fullPath: '/backoffice'
      preLoaderRoute: typeof BackofficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protecao/': {
      id: '/protecao/'
      path: '/protecao'
      fullPath: '/protecao/'
      preLoaderRoute: typeof ProtecaoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lavoura/': {
      id: '/lavoura/'
      path: '/lavoura'
      fullPath: '/lavoura/'
      preLoaderRoute: typeof LavouraIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protecao/confirmado': {
      id: '/protecao/confirmado'
      path: '/protecao/confirmado'
      fullPath: '/protecao/confirmado'
      preLoaderRoute: typeof ProtecaoConfirmadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lavoura/acao': {
      id: '/lavoura/acao'
      path: '/lavoura/acao'
      fullPath: '/lavoura/acao'
      preLoaderRoute: typeof LavouraAcaoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BackofficeRoute: BackofficeRoute,
  CadastroRoute: CadastroRoute,
  ComprovarRoute: ComprovarRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  GatilhoRoute: GatilhoRoute,
  OnboardingRoute: OnboardingRoute,
  PerfilRoute: PerfilRoute,
  ProgramasRoute: ProgramasRoute,
  LavouraAcaoRoute: LavouraAcaoRoute,
  ProtecaoConfirmadoRoute: ProtecaoConfirmadoRoute,
  LavouraIndexRoute: LavouraIndexRoute,
  ProtecaoIndexRoute: ProtecaoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
