/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RetificacaoRouteImport } from './routes/retificacao'
import { Route as ProgramasRouteImport } from './routes/programas'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as GerarRouteImport } from './routes/gerar'
import { Route as ExportarRouteImport } from './routes/exportar'
import { Route as DiagnosticoRouteImport } from './routes/diagnostico'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as BackofficeRouteImport } from './routes/backoffice'
import { Route as PortalRouteRouteImport } from './routes/portal/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as PortalImovelCarRouteImport } from './routes/portal/imovel.$car'

const RetificacaoRoute = RetificacaoRouteImport.update({
  id: '/retificacao',
  path: '/retificacao',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramasRoute = ProgramasRouteImport.update({
  id: '/programas',
  path: '/programas',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const GerarRoute = GerarRouteImport.update({
  id: '/gerar',
  path: '/gerar',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportarRoute = ExportarRouteImport.update({
  id: '/exportar',
  path: '/exportar',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoRoute = DiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const BackofficeRoute = BackofficeRouteImport.update({
  id: '/backoffice',
  path: '/backoffice',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRouteRoute = PortalRouteRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalImovelCarRoute = PortalImovelCarRouteImport.update({
  id: '/imovel/$car',
  path: '/imovel/$car',
  getParentRoute: () => PortalRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/portal': typeof PortalRouteRouteWithChildren
  '/backoffice': typeof BackofficeRoute
  '/cadastro': typeof CadastroRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/exportar': typeof ExportarRoute
  '/gerar': typeof GerarRoute
  '/mapa': typeof MapaRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRoute
  '/programas': typeof ProgramasRoute
  '/retificacao': typeof RetificacaoRoute
  '/portal/': typeof PortalIndexRoute
  '/portal/imovel/$car': typeof PortalImovelCarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/backoffice': typeof BackofficeRoute
  '/cadastro': typeof CadastroRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/exportar': typeof ExportarRoute
  '/gerar': typeof GerarRoute
  '/mapa': typeof MapaRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRoute
  '/programas': typeof ProgramasRoute
  '/retificacao': typeof RetificacaoRoute
  '/portal': typeof PortalIndexRoute
  '/portal/imovel/$car': typeof PortalImovelCarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/portal': typeof PortalRouteRouteWithChildren
  '/backoffice': typeof BackofficeRoute
  '/cadastro': typeof CadastroRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/exportar': typeof ExportarRoute
  '/gerar': typeof GerarRoute
  '/mapa': typeof MapaRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRoute
  '/programas': typeof ProgramasRoute
  '/retificacao': typeof RetificacaoRoute
  '/portal/': typeof PortalIndexRoute
  '/portal/imovel/$car': typeof PortalImovelCarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/portal'
    | '/backoffice'
    | '/cadastro'
    | '/configuracoes'
    | '/diagnostico'
    | '/exportar'
    | '/gerar'
    | '/mapa'
    | '/onboarding'
    | '/perfil'
    | '/programas'
    | '/retificacao'
    | '/portal/'
    | '/portal/imovel/$car'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/backoffice'
    | '/cadastro'
    | '/configuracoes'
    | '/diagnostico'
    | '/exportar'
    | '/gerar'
    | '/mapa'
    | '/onboarding'
    | '/perfil'
    | '/programas'
    | '/retificacao'
    | '/portal'
    | '/portal/imovel/$car'
  id:
    | '__root__'
    | '/'
    | '/portal'
    | '/backoffice'
    | '/cadastro'
    | '/configuracoes'
    | '/diagnostico'
    | '/exportar'
    | '/gerar'
    | '/mapa'
    | '/onboarding'
    | '/perfil'
    | '/programas'
    | '/retificacao'
    | '/portal/'
    | '/portal/imovel/$car'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PortalRouteRoute: typeof PortalRouteRouteWithChildren
  BackofficeRoute: typeof BackofficeRoute
  CadastroRoute: typeof CadastroRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DiagnosticoRoute: typeof DiagnosticoRoute
  ExportarRoute: typeof ExportarRoute
  GerarRoute: typeof GerarRoute
  MapaRoute: typeof MapaRoute
  OnboardingRoute: typeof OnboardingRoute
  PerfilRoute: typeof PerfilRoute
  ProgramasRoute: typeof ProgramasRoute
  RetificacaoRoute: typeof RetificacaoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/retificacao': {
      id: '/retificacao'
      path: '/retificacao'
      fullPath: '/retificacao'
      preLoaderRoute: typeof RetificacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programas': {
      id: '/programas'
      path: '/programas'
      fullPath: '/programas'
      preLoaderRoute: typeof ProgramasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gerar': {
      id: '/gerar'
      path: '/gerar'
      fullPath: '/gerar'
      preLoaderRoute: typeof GerarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exportar': {
      id: '/exportar'
      path: '/exportar'
      fullPath: '/exportar'
      preLoaderRoute: typeof ExportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico': {
      id: '/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof DiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backoffice': {
      id: '/backoffice'
      path: '/backoffice'
      fullPath: '/backoffice'
      preLoaderRoute: typeof BackofficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/imovel/$car': {
      id: '/portal/imovel/$car'
      path: '/imovel/$car'
      fullPath: '/portal/imovel/$car'
      preLoaderRoute: typeof PortalImovelCarRouteImport
      parentRoute: typeof PortalRouteRoute
    }
  }
}

interface PortalRouteRouteChildren {
  PortalIndexRoute: typeof PortalIndexRoute
  PortalImovelCarRoute: typeof PortalImovelCarRoute
}

const PortalRouteRouteChildren: PortalRouteRouteChildren = {
  PortalIndexRoute: PortalIndexRoute,
  PortalImovelCarRoute: PortalImovelCarRoute,
}

const PortalRouteRouteWithChildren = PortalRouteRoute._addFileChildren(
  PortalRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PortalRouteRoute: PortalRouteRouteWithChildren,
  BackofficeRoute: BackofficeRoute,
  CadastroRoute: CadastroRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DiagnosticoRoute: DiagnosticoRoute,
  ExportarRoute: ExportarRoute,
  GerarRoute: GerarRoute,
  MapaRoute: MapaRoute,
  OnboardingRoute: OnboardingRoute,
  PerfilRoute: PerfilRoute,
  ProgramasRoute: ProgramasRoute,
  RetificacaoRoute: RetificacaoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
